server:
  port: 8200
spring:
  application:
    name: springcloud-product-consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8300/eureka
feign:
  hystrix:
    enabled: true
